name: Fraud Detection Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-code:
    runs-on: ubuntu-latest
    
    # 1. INJECT FAKE ENV VARS FOR TESTING
    env:
      APP_NAME: "Test App"
      DEBUG_MODE: "True"
      ANOMALY_THRESHOLD: "0.005"
      INPUT_DIM: "8"
      MODEL_PATH: "models/autoencoder.pth"
      SCALER_PATH: "models/scaler.joblib"
      ENCODER_PATH: "models/encoder.joblib"
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # 2. GENERATE DUMMY ARTIFACTS
    - name: Generate Test Artifacts
      run: |
        # Create the missing directories
        mkdir -p data
        mkdir -p models
        
        # Now run the scripts to create the files
        python -m src.data_gen
        python -m src.train

    - name: Run Unit Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest tests/

    # --- NEW STEP: SAVE ARTIFACTS ---
    # We save the trained models so the next job can use them
    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-models
        path: models/
        retention-days: 1

  build-container:
    needs: test-code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    # --- NEW STEP: RETRIEVE ARTIFACTS ---
    # We download the models saved by the previous job
    - name: Download Model Artifacts
      uses: actions/download-artifact@v4
      with:
        name: trained-models
        path: models/
      
    - name: Build Docker Image
      run: |
        # Verify models exist before building (Optional debug step)
        ls -R models/
        
        docker build -t fraud-detector:latest .